### ISSUE TITLE
Role of cultivar in MutMap analysis

### ISSUE THREAD

**Issue by LeoVincenzi** [YuSugihara/MutMap#14]
Dear developers,
I'm using Mutmap to perform some analysis on a set of 4 F2 bulk (2 mutant and 2 wild type) and 2 parentals  (1 mutant and 1 wild type).
I was running the MutMap command with bam files:
```
mutmap -r genome.fasta -c Wild_type/alignment.bam -b Pool_1_Mut/alignment.bam -n 11 -o Pool_1_Mut
```

but what is not clear to me is the role of the cultivar (parental) in the final results. How does it affect the alignment and the variant calling of the bulk?
Moreover, I've tried to run each bulk with the opposite parental as cultivar, but I'm not sure if it was correct.

Thanks, 
Leonardo

**Comment by YuSugihara** [comment]
I'm sorry for the late response.

For the detailed information of pipeline, please refer to the original papers:
- https://www.nature.com/articles/nbt.2095
- https://doi.org/10.7717/peerj.13170

In short, the cultivar is used to calculate the SNP-index of mutant bulk because SNP-index is a measure of genetic distance of mutant bulk from cultivar sequence.
